name: Generate Blog List

on:
  push:
    branches:
      - main  # Change to the branch name you use if not "main"
      - master # Name to be changed in the future
  workflow_dispatch: # Optional, allows you to trigger the workflow manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up shell environment
      - name: Set up shell environment
        run: sudo chmod +x blog/generate-list.sh  # Make the script executable

      # Step 3: Run the script
      - name: Run generate-list.sh
        run: cd blog && ./generate-list.sh

      # Step 4: Commit and push changes
      - name: Commit and push updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add blog/list.json
          git commit -m "Update blog list via GitHub Actions" || echo "No changes to commit"
          git push
